apiVersion: v1
kind: Namespace
metadata:
  name: wiki
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wikijs
  namespace: wiki
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: requarks/wiki
          ports:
            - name: http-port
              containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: wikijs
  namespace: wiki
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: wikijs
